#!/usr/bin/env bash
# install ngix server

sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo echo "Shobandeisrael08" > /var/www/html/index.html
sudo service nginx start
